// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAghlihhxqoDEG2YKTzibC_jFzUmovjwOk',
    appId: '1:27192813127:web:5856df7698e094a8757362',
    messagingSenderId: '27192813127',
    projectId: 'flutter-projects-35730',
    authDomain: 'flutter-projects-35730.firebaseapp.com',
    storageBucket: 'flutter-projects-35730.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0oosOZco57fjFBXxrgEqnqf4g1dDf_Cw',
    appId: '1:27192813127:android:d7bc92cc04e36e77757362',
    messagingSenderId: '27192813127',
    projectId: 'flutter-projects-35730',
    storageBucket: 'flutter-projects-35730.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDReL_ol-vTpi8F4KJAClyjxoy4oUEry7Y',
    appId: '1:27192813127:ios:1bb7dffbbc4e7a45757362',
    messagingSenderId: '27192813127',
    projectId: 'flutter-projects-35730',
    storageBucket: 'flutter-projects-35730.appspot.com',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDReL_ol-vTpi8F4KJAClyjxoy4oUEry7Y',
    appId: '1:27192813127:ios:6f9e119510f55125757362',
    messagingSenderId: '27192813127',
    projectId: 'flutter-projects-35730',
    storageBucket: 'flutter-projects-35730.appspot.com',
    iosBundleId: 'com.example.pushApp.RunnerTests',
  );
}
